Repository PKUHPC/CraneSched, pull requests merged in 2024-12, with the labels that each got.

#379 fix<CraneCtld>: Exit on node configured without any partition.
  src/CraneCtld/CraneCtld.cpp
Labels: bug

#395 Bugfix: Check permission when update node
  protos/Crane.proto
  src/CraneCtld/CtldGrpcServer.cpp
Labels: bug

#362 Feat: Crun support pty
  CMakeLists.txt
  protos/PublicDefs.proto
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
  src/Craned/CMakeLists.txt
  src/Craned/CforedClient.cpp
  src/Craned/CforedClient.h
  src/Craned/TaskManager.cpp
  src/Craned/TaskManager.h
Labels: enhancement

#398 refactor: Add cleanup script in Python
  scripts/CraneMininet.py
  scripts/CraneMininet.yaml
  scripts/wipe_data.py
  scripts/wipe_data.sh
Labels: refactor

#400 fix: Skip Link-Local IPv6 Address
  src/CraneCtld/CraneCtld.cpp
  src/Utilities/PublicHeader/Network.cpp
  src/Utilities/PublicHeader/OS.cpp
Labels: bug

#409 Fix: Fix libcgroup configuring and DEB packaging size
  CMakeLists.txt
  dependencies/cmake/libcgroup/CMakeLists.txt
Labels: build

#413 feat: Add multiple GID support
  protos/PublicDefs.proto
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/DbClient.cpp
  src/Craned/TaskManager.cpp
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: enhancement
