Repository PKUHPC/CraneSched, pull requests merged in 2024-11, with the labels that each got.

#352 Doc: remove old gres config example
  etc/config.yaml
Labels: Doc

#353 Refactor: change cpack package file name
  CMakeLists.txt
Labels: build

#355 Bugfix: empty CRANE_PARTITION environment variable when task using default partition
  src/CraneCtld/CranedKeeper.cpp
Labels: bug

#350 Feat: Add GitHub Action for Building and Packaging
  .github/workflows/build.yaml
Labels: CI

#360 Bugfix: Fetch resource from total instead of available
  src/CraneCtld/TaskScheduler.cpp
Labels: bug

#358 Refactor: detect proxy environment variable on daemon start
  src/CraneCtld/CraneCtld.cpp
  src/Craned/Craned.cpp
  src/Utilities/PublicHeader/OS.cpp
  src/Utilities/PublicHeader/include/crane/OS.h
Labels: enhancement

#365 Fix: Fix free a locked lock when release cgroup
  src/Craned/CgroupManager.cpp
Labels: bug

#364 chore: add mimalloc allocator
  CMakeLists.txt
  dependencies/cmake/CMakeLists.txt
  dependencies/cmake/mimalloc/CMakeLists.txt
  src/CraneCtld/CMakeLists.txt
  src/Craned/CMakeLists.txt
  src/Misc/Pam/CMakeLists.txt
Labels: enhancement, build

#368 fix: Fix sigsegv in cranectld
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/TaskScheduler.h
Labels: bug

#321 Separate Authentication and Modification in AccountManager
  CMakeLists.txt
  dependencies/cmake/grpc/CMakeLists.txt
  dependencies/cmake/libcgroup/CMakeLists.txt
  dependencies/cmake/mimalloc/CMakeLists.txt
  protos/Crane.proto
  protos/PublicDefs.proto
  src/CraneCtld/AccountManager.cpp
  src/CraneCtld/AccountManager.h
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/CtldPreCompiledHeader.h
  src/CraneCtld/TaskScheduler.cpp
Labels: refactor, build

#333 Feat: Add ascend support and refactor
  protos/Crane.proto
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CtldPreCompiledHeader.h
  src/Craned/CforedClient.cpp
  src/Craned/CgroupManager.cpp
  src/Craned/CgroupManager.h
  src/Craned/Craned.cpp
  src/Craned/CranedPreCompiledHeader.h
  src/Craned/CranedPublicDefs.h
  src/Craned/CranedServer.cpp
  src/Craned/DeviceManager.cpp
  src/Craned/DeviceManager.h
  src/Craned/TaskManager.cpp
  src/Craned/TaskManager.h
  src/Misc/Pam/PamUtil.cpp
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: enhancement, refactor

#359 Refactor: Replace libevent with libuvw in Craned
  dependencies/cmake/CMakeLists.txt
  src/CraneCtld/AccountManager.cpp
  src/CraneCtld/CMakeLists.txt
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CranedMetaContainer.cpp
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/DbClient.cpp
  src/CraneCtld/DbClient.h
  src/CraneCtld/TaskScheduler.cpp
  src/Craned/CMakeLists.txt
  src/Craned/CforedClient.cpp
  src/Craned/CgroupManager.cpp
  src/Craned/CgroupManager.h
  src/Craned/Craned.cpp
  src/Craned/CranedPreCompiledHeader.h
  src/Craned/CranedPublicDefs.h
  src/Craned/CranedServer.cpp
  src/Craned/CranedServer.h
  src/Craned/CtldClient.cpp
  src/Craned/CtldClient.h
  src/Craned/TaskManager.cpp
  src/Craned/TaskManager.h
Labels: refactor, build
