Repository PKUHPC/CraneSched, pull requests merged in 2025-04, with the labels that each got.

#456 feat: Add Vault
  .clang-tidy
  CMakeLists.txt
  dependencies/cmake/CMakeLists.txt
  dependencies/cmake/libvault/CMakeLists.txt
  etc/database.yaml
  src/CraneCtld/CMakeLists.txt
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CtldPreCompiledHeader.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/Security/VaultClient.cpp
  src/CraneCtld/Security/VaultClient.h
  src/Craned/Craned.cpp
Labels: enhancement, build

#464 chore: Add clang-format check.
  .clang-format
  .clang-tidy
  .coderabbit.yaml
  .github/workflows/format.yaml
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CranedKeeper.h
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/DbClient.h
  src/CraneCtld/EmbeddedDbClient.cpp
  src/CraneCtld/Security/VaultClient.h
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
  src/Craned/CranedServer.cpp
  src/Craned/CtldClient.cpp
  src/Craned/DeviceManager.cpp
  src/Craned/TaskManager.h
  src/Utilities/PluginClient/PluginClient.cpp
  src/Utilities/PluginClient/include/crane/PluginClient.h
  src/Utilities/PublicHeader/OS.cpp
  src/Utilities/PublicHeader/PublicHeader.cpp
  src/Utilities/PublicHeader/include/crane/Logger.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: CI

#460 feat: Add cbatch --open-mode option
  etc/config.yaml
  protos/PublicDefs.proto
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
  src/Craned/TaskManager.cpp
Labels: enhancement

#472 chore: Auto format file and commit.
  .clang-format
  .clang-tidy
  .github/workflows/build.yaml
  .github/workflows/format.yaml
  src/CraneCtld/TaskScheduler.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: CI, test-passed

#483 chore: Fix CI for pull requests from forked repo
  .github/workflows/build.yaml
  .github/workflows/format.yaml
  .github/workflows/label.yaml
  src/Craned/TaskManager.cpp
Labels: CI

#488 fix: Change the permissions of the system-generated job script to the submitting user
  src/Craned/TaskManager.cpp
Labels: test-passed

#351 Dev/reservation
  protos/Crane.proto
  protos/PublicDefs.proto
  src/CraneCtld/CranedMetaContainer.cpp
  src/CraneCtld/CranedMetaContainer.h
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/DbClient.cpp
  src/CraneCtld/EmbeddedDbClient.cpp
  src/CraneCtld/EmbeddedDbClient.h
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: enhancement

#491 fix: delete user
  src/CraneCtld/DbClient.cpp
Labels: bug, test-passed

#490 feat: Add crane user for CraneCtld
  CMakeLists.txt
  etc/cranectld.service.in
  etc/craned.service.in
  src/CraneCtld/CraneCtld.cpp
Labels: test-passed
