Repository PKUHPC/CraneSched, pull requests merged in 2025-05, with the labels that each got.

#475 refactor: Refactor craned up-line logic.
  protos/Crane.proto
  protos/PublicDefs.proto
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CranedKeeper.h
  src/CraneCtld/CranedMetaContainer.cpp
  src/CraneCtld/CranedMetaContainer.h
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/DbClient.cpp
  src/Craned/Craned.cpp
  src/Craned/CranedPublicDefs.h
  src/Craned/CranedServer.cpp
  src/Craned/CranedServer.h
  src/Craned/CtldClient.cpp
  src/Craned/CtldClient.h
  src/Craned/TaskManager.cpp
  src/Craned/TaskManager.h
  src/Utilities/PublicHeader/GrpcHelper.cpp
  src/Utilities/PublicHeader/include/crane/GrpcHelper.h
  src/Utilities/PublicHeader/include/crane/Logger.h
Labels: refactor, test-passed

#497 fix: Fix crun timeout.
  src/CraneCtld/CtldGrpcServer.cpp
  src/Craned/TaskManager.cpp
Labels: bug, test-passed

#500 Fix: Node select
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
Labels: test-passed

#461 refactor: Change CgroupManager to stateless, add jobmanager.
  .clang-format
  CMakeLists.txt
  protos/Crane.proto
  protos/PublicDefs.proto
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CranedKeeper.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/TaskScheduler.cpp
  src/Craned/CMakeLists.txt
  src/Craned/CgroupManager.cpp
  src/Craned/CgroupManager.h
  src/Craned/Craned.cpp
  src/Craned/CranedPublicDefs.h
  src/Craned/CranedServer.cpp
  src/Craned/JobManager.cpp
  src/Craned/JobManager.h
  src/Craned/TaskManager.cpp
  src/Craned/TaskManager.h
  src/Misc/BPF/cgroup_dev_bpf.c
  src/Utilities/PublicHeader/Logger.cpp
  src/Utilities/PublicHeader/PublicHeader.cpp
  src/Utilities/PublicHeader/include/crane/Logger.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
  src/Utilities/PublicHeader/include/crane/String.h
Labels: enhancement, refactor, test-passed

#502 chore: Fix clang format.
  .github/workflows/format.yaml
  src/CraneCtld/EmbeddedDbClient.h
Labels: CI, test-passed

#508 fix: Fix error env returned.
  src/Craned/CranedServer.cpp
Labels: bug, test-passed

#509 fix: Set keepalive for Cforedclient.
  src/Craned/CforedClient.cpp
Labels: bug, test-passed

#510 fix: handle empty res_avail on node
  src/CraneCtld/TaskScheduler.cpp
Labels: test-passed

#458 Add cbatch/crun/calloc add --exclusive
  protos/PublicDefs.proto
  src/CraneCtld/CranedKeeper.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/DbClient.cpp
  src/CraneCtld/DbClient.h
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
Labels: test-passed

#439 feat: Add power-control interface
  protos/Crane.proto
  protos/Plugin.proto
  protos/PublicDefs.proto
  src/CraneCtld/CranedMetaContainer.cpp
  src/CraneCtld/CtldGrpcServer.cpp
  src/CraneCtld/CtldGrpcServer.h
  src/CraneCtld/CtldPublicDefs.h
  src/Craned/CgroupManager.cpp
  src/Craned/Craned.cpp
  src/Craned/CranedPublicDefs.h
  src/Craned/CtldClient.cpp
  src/Utilities/PluginClient/PluginClient.cpp
  src/Utilities/PluginClient/include/crane/PluginClient.h
  src/Utilities/PublicHeader/Network.cpp
  src/Utilities/PublicHeader/include/crane/Network.h
Labels: enhancement
