Repository PKUHPC/CraneSched, pull requests merged in 2025-09, with the labels that each got.

#612 fix: Craned free invalid job when register
  src/CraneCtld/TaskScheduler.cpp
  src/Craned/Core/JobManager.cpp
Labels: bug, test-passed

#613 fix: Fix error code
  src/Craned/Supervisor/TaskManager.cpp
Labels: bug

#618 fix: no longer store alloc_res
  src/CraneCtld/TaskScheduler.cpp
Labels: refactor, test-passed

#623 feat: Change TLS to use a single CA.
  etc/config.yaml
  scripts/vault.sh
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/RpcService/CtldGrpcServer.cpp
  src/CraneCtld/Security/VaultClient.cpp
  src/CraneCtld/Security/VaultClient.h
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedPublicDefs.h
  src/Craned/Core/CranedServer.cpp
  src/Craned/Core/JobManager.cpp
  src/Craned/Supervisor/Supervisor.cpp
  src/Craned/Supervisor/SupervisorPublicDefs.h
  src/Utilities/PublicHeader/GrpcHelper.cpp
  src/Utilities/PublicHeader/include/crane/GrpcHelper.h
Labels: test-passed
