Repository PKUHPC/CraneSched, pull requests merged in 2025-08, with the labels that each got.

#534 Dev/nodehash
  etc/config.yaml
  protos/PublicDefs.proto
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/RpcService/CtldForInternalServer.cpp
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedPublicDefs.h
  src/Craned/Core/CtldClient.cpp
  src/Utilities/PublicHeader/CMakeLists.txt
  src/Utilities/PublicHeader/String.cpp
  src/Utilities/PublicHeader/include/crane/String.h
Labels: test-passed

#574 feat: Split cgroup into 3 levels
  .clang-tidy
  src/Craned/Core/CgroupManager.cpp
  src/Craned/Core/CgroupManager.h
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedServer.cpp
  src/Craned/Core/JobManager.cpp
  src/Craned/Core/SupervisorKeeper.h
  src/Misc/BPF/cgroup_dev_bpf.c
Labels: test-passed

#582 feat: Add unified entry for cgroup creation
  src/Craned/Core/CgroupManager.cpp
  src/Craned/Core/CgroupManager.h
  src/Craned/Core/JobManager.cpp
Labels: test-passed

#581 refactor: ctld grpc internal server to ctld server
  src/CraneCtld/CMakeLists.txt
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/RpcService/CtldForInternalServer.cpp
  src/CraneCtld/RpcService/CtldForInternalServer.h
  src/CraneCtld/RpcService/CtldGrpcServer.cpp
  src/CraneCtld/RpcService/CtldGrpcServer.h
Labels: test-passed

#420 feat: Add TLS PKI
  etc/config.yaml
  etc/database.yaml
  protos/Crane.proto
  protos/PublicDefs.proto
  protos/Supervisor.proto
  src/CraneCtld/AccountManager.cpp
  src/CraneCtld/AccountManager.h
  src/CraneCtld/CMakeLists.txt
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/DbClient.cpp
  src/CraneCtld/RpcService/CranedKeeper.cpp
  src/CraneCtld/RpcService/CtldGrpcServer.cpp
  src/CraneCtld/RpcService/CtldGrpcServer.h
  src/CraneCtld/Security/VaultClient.cpp
  src/CraneCtld/Security/VaultClient.h
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedForPamServer.cpp
  src/Craned/Core/CranedPublicDefs.h
  src/Craned/Core/CranedServer.cpp
  src/Craned/Core/CtldClient.cpp
  src/Craned/Core/JobManager.cpp
  src/Craned/Supervisor/CforedClient.cpp
  src/Craned/Supervisor/Supervisor.cpp
  src/Craned/Supervisor/SupervisorPublicDefs.h
  src/Utilities/PublicHeader/GrpcHelper.cpp
  src/Utilities/PublicHeader/String.cpp
  src/Utilities/PublicHeader/include/crane/GrpcHelper.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
  src/Utilities/PublicHeader/include/crane/String.h
Labels: enhancement, build, test-passed

#591 fix: Resend status change if rpc failure
  src/Craned/Core/CtldClient.cpp
  src/Craned/Supervisor/CranedClient.cpp
Labels: bug, test-passed

#592 fix: CtldClientStateMachine with ping
  src/CraneCtld/RpcService/CranedKeeper.cpp
  src/CraneCtld/RpcService/CranedKeeper.h
  src/CraneCtld/TaskScheduler.cpp
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedPublicDefs.h
  src/Craned/Core/CranedServer.h
  src/Craned/Core/CtldClient.cpp
  src/Craned/Core/CtldClient.h
  src/Utilities/PublicHeader/include/crane/PublicHeader.h
Labels: bug, test-passed

#601 fix: Reservation db not closed
  src/CraneCtld/EmbeddedDbClient.cpp
Labels: bug, test-passed

#602 feat: Add cache and split ci into two jobs
  .github/workflows/build.yaml
Labels: test-passed

#603 fix: Add bundle extraction step in build workflow
  .github/workflows/build.yaml
Labels: test-passed

#604 fix: Add try-catch to mongodb operation.
  src/CraneCtld/DbClient.cpp
  src/CraneCtld/TaskScheduler.cpp
  src/Craned/Common/CgroupManager.cpp
  src/Craned/Common/CgroupManager.h
  src/Craned/Common/CommonPublicDefs.h
  src/Craned/Common/DeviceManager.cpp
  src/Craned/Common/DeviceManager.h
  src/Craned/Core/Craned.cpp
  src/Craned/Core/CranedPublicDefs.h
  src/Craned/Core/CranedServer.h
  src/Craned/Core/JobManager.cpp
  src/Craned/Core/JobManager.h
  src/Craned/Supervisor/CforedClient.cpp
  src/Craned/Supervisor/CforedClient.h
  src/Craned/Supervisor/CranedClient.cpp
  src/Craned/Supervisor/CranedClient.h
  src/Craned/Supervisor/Supervisor.cpp
  src/Craned/Supervisor/SupervisorPublicDefs.h
  src/Craned/Supervisor/SupervisorServer.cpp
  src/Craned/Supervisor/SupervisorServer.h
  src/Craned/Supervisor/TaskManager.cpp
  src/Craned/Supervisor/TaskManager.h
Labels: bug, test-passed
