Repository PKUHPC/CraneSched, pull requests merged in 2025-01, with the labels that each got.

#419 Bugfix/bpf compilation
  CMakeLists.txt
  CMakeModule/FindBPF.cmake
  src/Craned/CMakeLists.txt
  src/Misc/BPF/CMakeLists.txt
  src/Misc/CMakeLists.txt
  src/Misc/Pam/PamUtil.cpp
Labels: bug, build

#319 Dev/sched algo
  .clang-format
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/TaskScheduler.cpp
  src/CraneCtld/TaskScheduler.h
  src/Craned/CgroupManager.cpp
  src/Craned/Craned.cpp
Labels: enhancement, refactor

#370 User QoS resource total limit
  dependencies/cmake/CMakeLists.txt
  dependencies/cmake/parallel-hashmap/CMakeLists.txt
  src/CraneCtld/AccountManager.cpp
  src/CraneCtld/AccountMetaContainer.cpp
  src/CraneCtld/AccountMetaContainer.h
  src/CraneCtld/CMakeLists.txt
  src/CraneCtld/CraneCtld.cpp
  src/CraneCtld/CtldPreCompiledHeader.h
  src/CraneCtld/CtldPublicDefs.h
  src/CraneCtld/TaskScheduler.cpp
Labels: enhancement

#418 feat: Add the functionality to modify the default user account.
  protos/PublicDefs.proto
  src/CraneCtld/AccountManager.cpp
  src/CraneCtld/AccountManager.h
  src/CraneCtld/CtldGrpcServer.cpp
Labels: enhancement

#408 fetch feasible resource from res_avail first
  src/CraneCtld/TaskScheduler.cpp
Labels: bug
